pipeline {
    agent any

    stages {
        stage('Test') {
      agent {
        docker {
          image 'maven:3.8.6-openjdk-11-slim'
        }
      }
      steps {
        echo "Job: ${env.JOB_NAME}"
        echo "Branch: ${env.BRANCH_NAME}"
        sh 'make test'
      }
        }
    stage('Lint') {
      agent {
        docker {
          image 'maven:3.8.6-openjdk-11-slim'
        }
      }
      steps {
        sh 'apt-get update && apt-get install -y make && rm -rf /var/lib/apt/lists/*' // Instala make dentro del contenedor Docker

        sh 'make lint'
      }
    }
    }
}
